import {readFileSync, writeFileSync, mkdirSync, copyFileSync} from 'node:fs';
// Bundle local modules only; Obsidian supplies its API and CodeMirror at runtime.
const ids = ['parser','header','editing','outline','main'];
const modules = ids.map(id => `${JSON.stringify('./'+id)}: function(module,exports,require) {\n${readFileSync('src/'+id+'.js','utf8')}\n}`).join(',\n');
const icons = readFileSync('src/icons.json','utf8');
writeFileSync('main.js', `/* Evoldown v1.2.0 — generated by build.mjs */\n'use strict';\nconst externalRequire = require;\nconst factories = {${modules},'./icons.json':function(module){module.exports=${icons};}};\nconst cache = {};\nfunction load(id){if(!factories[id])return externalRequire(id);if(cache[id])return cache[id].exports;const module={exports:{}};cache[id]=module;factories[id](module,module.exports,load);return module.exports;}\nmodule.exports=load('./main');\n`);
mkdirSync('dist/evoldown',{recursive:true});
for (const file of ['main.js','manifest.json','styles.css']) copyFileSync(file,'dist/evoldown/'+file);
console.log('Built dist/evoldown');
