/* Evoldown v1.2.1 — generated by build.mjs */
'use strict';
const externalRequire = require;
const factories = {"./parser": function(module,exports,require) {
'use strict';
const TYPES = new Set(['d', 'e', 't', 'v', 'c']);
// Quoted fields allow spaces; malformed syntax remains ordinary Markdown.
function parseHeading(line) {
  const match = /^ {0,3}#([a-z])\s+(.+?)\s*$/.exec(line);
  if (!match || !TYPES.has(match[1])) return null;
  const fields = [];
  const expression = /"((?:\\.|[^"\\])*)"|'((?:\\.|[^'\\])*)'|(\S+)/gy;
  let position = 0;
  while (position < match[2].length) {
    expression.lastIndex = position;
    const token = expression.exec(match[2]);
    if (!token) return null;
    if (token[3] && /^["']/.test(token[3])) return null;
    fields.push((token[1] ?? token[2] ?? token[3]).replace(/\\([\\"'])/g, '$1'));
    position = expression.lastIndex;
    if (position < match[2].length && !/\s/.test(match[2][position])) return null;
    while (/\s/.test(match[2][position] ?? '') && position < match[2].length) position++;
  }
  const custom = match[1] === 'c';
  if (fields.some(x => !x) || fields.length < (custom ? 2 : 1) || fields.length > (custom ? 3 : 2)) return null;
  return { type: match[1], label: custom ? fields[0] : '', title: fields[custom ? 1 : 0], reference: fields[custom ? 2 : 1] || '' };
}
function parseDocument(source) {
  const lines = source.split(/\r?\n/);
  const blocks = [];
  let current = null, fence = null, frontmatter = lines[0] === '---', comment = false, html = false;
  const close = end => { if (current) { current.end = end; while (current.end > current.start + 1 && !lines[current.end - 1].trim()) current.end--; blocks.push(current); current = null; } };
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (frontmatter) { if (i > 0 && /^(---|\.\.\.)\s*$/.test(line)) frontmatter = false; continue; }
    if (fence) { if (new RegExp('^ {0,3}' + fence.char + '{' + fence.size + ',}\\s*$').test(line)) fence = null; continue; }
    if (comment) { if (line.includes('-->') || line.includes('%%')) comment = false; continue; }
    if (html) { if (!line.trim()) html = false; continue; }
    if (/^ {0,3}(<!--|%%)/.test(line)) { comment = !/<!--.*-->|%%.*%%/.test(line); continue; }
    if (/^ {0,3}<\/?[a-zA-Z][\s>]/.test(line) || /^ {0,3}<(div|section|table|pre|script|style)\b/i.test(line)) { html = true; continue; }
    const f = /^ {0,3}(`{3,}|~{3,})(.*)$/.exec(line);
    if (f && !(f[1][0] === '`' && f[2].includes('`'))) { fence = {char:f[1][0],size:f[1].length}; continue; }
    const heading = parseHeading(line);
    if (heading) { close(i); current = {...heading, start:i, end:lines.length}; }
    else if (/^ {0,3}#{1,6}(?:\s|$)/.test(line)) close(i);
    else if (i > 0 && /^ {0,3}(?:=+|-+)\s*$/.test(line) && lines[i-1].trim()) close(i-1);
  }
  close(lines.length);
  return {lines, blocks};
}
function resolveReference(blocks, title) { return blocks.find(block => block.title === title); }
module.exports = {parseHeading, parseDocument, resolveReference};

},
"./header": function(module,exports,require) {
'use strict';
const icons = require('./icons.json');
const {resolveReference} = require('./parser');
function icon(doc, type) {
  const badge = doc.createElement('span');
  badge.className = 'evoldown-icon evoldown-type-' + type;
  badge.setAttribute('aria-hidden', 'true');
  const svg = doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  for (const data of icons[type] || icons.c) {
    const path = doc.createElementNS(svg.namespaceURI, 'path');
    path.setAttribute('d', data); path.setAttribute('fill', 'currentColor'); svg.append(path);
  }
  badge.append(svg); return badge;
}
function createHeader(doc, block, blocks, navigate, level = 6, inline = false) {
  level = Number.isInteger(level) && level >= 1 && level <= 6 ? level : 6;
  const header = doc.createElement(inline ? 'span' : `h${level}`);
  header.className = 'evoldown-heading';
  header.dataset.level = String(level);
  if (!inline) header.setAttribute('data-heading', block.title);
  if (inline) { header.setAttribute('role', 'heading'); header.setAttribute('aria-level', String(level)); }
  header.append(icon(doc, block.type));
  if (block.label) { const label = doc.createElement('span'); label.className = 'evoldown-label'; label.textContent = block.label; header.append(label); }
  const title = doc.createElement('span'); title.className = 'evoldown-title'; title.textContent = block.title; header.append(title);
  if (block.reference) {
    const chain = doc.createElement('span'); chain.className = 'evoldown-chain'; chain.setAttribute('aria-hidden','true');
    const svg = doc.createElementNS('http://www.w3.org/2000/svg','svg'); svg.setAttribute('viewBox','0 0 24 24');
    const path = doc.createElementNS(svg.namespaceURI,'path');
    path.setAttribute('d','M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2');
    path.setAttribute('fill','none'); path.setAttribute('stroke','currentColor'); path.setAttribute('stroke-width','2'); svg.append(path); chain.append(svg); header.append(chain);
    const target = resolveReference(blocks, block.reference);
    const ref = doc.createElement('button'); ref.type = 'button'; ref.className = 'evoldown-reference';
    ref.setAttribute('aria-label', '跳转到：' + block.reference);
    if (target) { ref.append(icon(doc, target.type)); ref.addEventListener('click', event => {event.preventDefault(); event.stopPropagation(); navigate(target);}); }
    else { ref.disabled = true; ref.classList.add('is-unresolved'); ref.title = '当前笔记中未找到此标题'; }
    const name = doc.createElement('span'); name.textContent = block.reference; ref.append(name); header.append(ref);
  }
  return header;
}
module.exports = {createHeader};

},
"./editing": function(module,exports,require) {
'use strict';
// Translate the rendered character offset back through quotes and escape sequences.
function sourceFieldOffset(line, fieldIndex, displayOffset) {
  const prefix = /^ {0,3}#[a-z]\s+/.exec(line);
  if (!prefix) return 0;
  const fields = [...line.slice(prefix[0].length).matchAll(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\S+/g)];
  const field = fields[fieldIndex];
  if (!field) return prefix[0].length;
  const quoted = /^["']/.test(field[0]);
  const raw = quoted ? field[0].slice(1,-1) : field[0];
  let source = 0, displayed = 0;
  while (source < raw.length && displayed < displayOffset) {
    if (raw[source] === '\\' && /[\\"']/.test(raw[source+1] || '')) source++;
    source++; displayed++;
  }
  return prefix[0].length + field.index + (quoted ? 1 : 0) + source;
}
function clickedTextOffset(element, event) {
  if (!Number.isFinite(event.clientX) || !Number.isFinite(event.clientY) || event.detail === 0) return 0;
  const doc = element.ownerDocument;
  const point = doc.caretPositionFromPoint?.(event.clientX,event.clientY);
  const caret = point ? {startContainer:point.offsetNode,startOffset:point.offset} : doc.caretRangeFromPoint?.(event.clientX,event.clientY);
  if (caret && element.contains(caret.startContainer)) {
    const range = doc.createRange();
    range.selectNodeContents(element); range.setEnd(caret.startContainer,caret.startOffset);
    return range.toString().length;
  }
  // Noneditable CodeMirror widgets can be excluded by browser caret hit testing.
  // These fields contain one plain text node: use its glyph rectangles as fallback.
  const text = element.firstChild;
  if (!text || text.nodeType !== 3) return 0;
  const range = doc.createRange();
  let best = 0, distance = Infinity, offset = 0;
  for (const character of text.textContent) {
    const end = offset + character.length;
    range.setStart(text,offset); range.setEnd(text,end);
    for (const rect of range.getClientRects()) {
      const dy = Math.max(rect.top-event.clientY,0,event.clientY-rect.bottom);
      for (const [x,index] of [[rect.left,offset],[rect.right,end]]) {
        const score = dy * 10000 + Math.abs(event.clientX-x);
        if (score < distance) {distance=score;best=index;}
      }
    }
    offset = end;
  }
  return best;
}
module.exports = {sourceFieldOffset,clickedTextOffset};

},
"./outline": function(module,exports,require) {
'use strict';
const {parseDocument} = require('./parser');
function outlineHeadings(source, level) {
  const {lines,blocks} = parseDocument(source);
  const offsets = [0];
  for (let i = 0; i < source.length; i++) if (source[i] === '\n') offsets.push(i+1);
  return blocks.map(block => {
    const col = lines[block.start].indexOf('#');
    return {heading:block.title,level,position:{
      start:{line:block.start,col,offset:offsets[block.start]+col},
      end:{line:block.start,col:lines[block.start].length,offset:offsets[block.start]+lines[block.start].length}
    }};
  });
}
// Obsidian has no public heading-provider hook. Add reversible in-memory entries
// to the metadata consumed by the core Outline; never rewrite vault files.
class OutlineBridge {
  constructor(plugin) {
    this.plugin = plugin; this.app = plugin.app;
    this.records = new Map(); this.owned = new WeakSet(); this.revisions = new WeakMap();
    this.active = true; this.publishing = false;
  }
  start() {
    this.plugin.registerEvent(this.app.metadataCache.on('changed',(file,source,cache) => {
      if (!this.active || this.publishing || file.extension !== 'md') return;
      this.revisions.set(file,(this.revisions.get(file)||0)+1);
      this.apply(file,source,cache);
    }));
    this.plugin.registerEvent(this.app.vault.on('delete',file => {
      this.revisions.set(file,(this.revisions.get(file)||0)+1);
      const record = this.records.get(file);
      if (record) this.clean(record.cache);
      this.records.delete(file);
    }));
    this.plugin.registerEvent(this.app.workspace.on('file-open',file => { if (file?.extension === 'md') void this.read(file); }));
    this.plugin.register(() => this.stop());
    this.app.workspace.onLayoutReady(() => { void this.scan(); });
  }
  async scan() {
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (!this.active) break;
      await this.read(file);
    }
  }
  async read(file) {
    if (!this.active) return;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache) return; // The normal changed event handles newly indexed files.
    const revision = (this.revisions.get(file)||0)+1;
    this.revisions.set(file,revision);
    try {
      const source = await this.app.vault.cachedRead(file);
      if (this.active && this.revisions.get(file) === revision && this.app.metadataCache.getFileCache(file) === cache) this.apply(file,source,cache);
    } catch (error) { if (this.active) console.warn('Evoldown: unable to index outline for',file.path,error); }
  }
  clean(cache) {
    if (!cache.headings) return false;
    const original = cache.headings;
    const remaining = original.filter(heading => !this.owned.has(heading));
    if (remaining.length === original.length) return false;
    if (remaining.length) cache.headings = remaining;
    else delete cache.headings;
    return true;
  }
  apply(file,source,cache) {
    if (!this.active || typeof source !== 'string' || !cache) return;
    const previous = this.records.get(file);
    if (previous && previous.cache !== cache) this.clean(previous.cache);
    const removed = this.clean(cache);
    const custom = outlineHeadings(source,this.plugin.settings.headingLevel);
    for (const heading of custom) this.owned.add(heading);
    if (custom.length) {
      cache.headings = [...(cache.headings||[]),...custom].sort((a,b)=>a.position.start.offset-b.position.start.offset);
      this.records.set(file,{source,cache});
    } else this.records.delete(file);
    if (custom.length || removed) this.notify(file,source,cache);
  }
  notify(file,source,cache) {
    this.publishing = true;
    try { this.app.metadataCache.trigger('changed',file,source,cache); }
    finally { this.publishing = false; }
  }
  refresh() {
    for (const [file,record] of this.records) {
      if (this.app.metadataCache.getFileCache(file) === record.cache) this.apply(file,record.source,record.cache);
    }
  }
  stop() {
    this.active = false;
    for (const [file,record] of this.records) {
      if (this.clean(record.cache)) this.notify(file,record.source,record.cache);
    }
    this.records.clear();
  }
}
module.exports = {outlineHeadings,OutlineBridge};

},
"./pdf-export": function(module,exports,require) {
'use strict';
const {parseDocument} = require('./parser');
const {createHeader} = require('./header');
let renderId = 0;
function preparePrintSource(source) {
  const {blocks} = parseDocument(source);
  const lines = source.split(/\r?\n/);
  const marker = 'evoldown-print-' + (++renderId);
  // Render the whole document in one pass so footnotes, reference-style links,
  // lists, tables and embeds retain their normal Markdown context.
  blocks.forEach((block,index) => {
    lines[block.start] = `\n<div data-${marker}="${index}"></div>\n`;
  });
  return {source:lines.join('\n'),blocks,marker};
}
async function renderPdfExport(plugin, element, context, renderer, RenderChild) {
  // Native PDF export supplies no section information. Only handle its full-note
  // root; ordinary MarkdownRenderer calls and partial embeds must stay untouched.
  if (!element.matches('.markdown-preview-view') || !element.parentElement?.classList.contains('print')) return false;
  const file = plugin.app.vault.getFileByPath(context.sourcePath);
  if (!file) return false;
  const prepared = preparePrintSource(await plugin.app.vault.cachedRead(file));
  if (!prepared.blocks.length) return false;
  const container = element.ownerDocument.createElement('div');
  container.dataset.evoldownRender = 'true';
  const child = new RenderChild(container); context.addChild(child);
  await renderer.render(plugin.app,prepared.source,container,context.sourcePath,child);
  const placeholders = container.querySelectorAll(`[data-${prepared.marker}]`);
  if (placeholders.length !== prepared.blocks.length) throw new Error('Evoldown: PDF heading placeholders were not preserved by the Markdown renderer.');
  for (const placeholder of placeholders) {
    const index = Number(placeholder.getAttribute('data-' + prepared.marker));
    const block = prepared.blocks[index];
    const header = createHeader(element.ownerDocument,block,prepared.blocks,()=>{},plugin.settings.headingLevel);
    header.classList.add('evoldown-print-heading');
    placeholder.replaceWith(header);
  }
  // With "Include file name" enabled, Obsidian inserts a direct H1 before the
  // wrapped note contents. Keep that exact element without duplicating it.
  const filename = element.firstElementChild?.tagName === 'H1' ? element.firstElementChild : null;
  element.replaceChildren(...(filename ? [filename,container] : [container]));
  return true;
}
module.exports = {preparePrintSource,renderPdfExport};

},
"./main": function(module,exports,require) {
'use strict';
const {Plugin, MarkdownRenderer, MarkdownRenderChild, MarkdownView, editorLivePreviewField, PluginSettingTab, Setting} = require('obsidian');
const {StateField, StateEffect} = require('@codemirror/state');
const {Decoration, EditorView, WidgetType, ViewPlugin} = require('@codemirror/view');
const {parseDocument} = require('./parser');
const {createHeader} = require('./header');
const {sourceFieldOffset, clickedTextOffset} = require('./editing');
const {renderPdfExport} = require('./pdf-export');
const {OutlineBridge} = require('./outline');
const refreshHeadings = StateEffect.define();
function headingLevel(value) { return Number.isInteger(value) && value >= 1 && value <= 6 ? value : 6; }
class EvoldownSettingTab extends PluginSettingTab {
  constructor(app, plugin) { super(app, plugin); this.plugin = plugin; }
  display() {
    this.containerEl.empty();
    new Setting(this.containerEl)
      .setName('标题级别')
      .setDesc('所有自定义标题使用此级别的主题样式，修改后立即生效。')
      .addDropdown(dropdown => {
        for (let level = 1; level <= 6; level++) dropdown.addOption(String(level), `H${level}（${level} 级标题）`);
        dropdown.setValue(String(this.plugin.settings.headingLevel))
          .onChange(async value => { await this.plugin.setHeadingLevel(Number(value)); });
      });
  }
}
class HeadingWidget extends WidgetType {
  constructor(block, blocks, level) { super(); this.block = block; this.blocks = blocks; this.level = level; }
  eq(other) { return JSON.stringify([this.block,this.blocks,this.level]) === JSON.stringify([other.block,other.blocks,other.level]); }
  toDOM(view) {
    const header = createHeader(view.dom.ownerDocument, this.block, this.blocks, target => {
      const position = view.state.doc.line(target.start + 1).from;
      view.dispatch({selection:{anchor:position}, effects:EditorView.scrollIntoView(position,{y:'center'})}); view.focus();
    }, this.level, true);
    const enableEditing = (element, fieldIndex, name) => {
      element.classList.add('evoldown-editable-title');
      element.setAttribute('role', 'button');
      element.setAttribute('tabindex', '0');
      element.setAttribute('aria-label', '编辑' + name + '：' + element.textContent);
      element.setAttribute('title', '单击编辑' + name);
      element.addEventListener('mousedown', event => {
        if (event.button === 0) event.preventDefault();
      });
      const edit = event => {
        event.preventDefault();
        event.stopPropagation();
        const offset = fieldIndex === null ? 0 : clickedTextOffset(element, event);
        const line = view.state.doc.line(this.block.start + 1);
        const sourceOffset = fieldIndex === null ? line.text.indexOf('#') + 2 : sourceFieldOffset(line.text,fieldIndex,offset);
        view.dispatch({selection:{anchor:line.from + sourceOffset}});
        view.focus();
      };
      element.addEventListener('click', edit);
      element.addEventListener('keydown', event => {
        if (event.key === 'Enter' || event.key === ' ') edit(event);
      });
    };
    const typeIcon = header.children[0];
    typeIcon.setAttribute('aria-hidden', 'false');
    enableEditing(typeIcon, null, '标题类型 #' + this.block.type);
    enableEditing(header.querySelector('.evoldown-title'), this.block.type === 'c' ? 1 : 0, '标题');
    const label = header.querySelector('.evoldown-label');
    if (label) enableEditing(label, 0, '自定义标签');
    return header;
  }
  ignoreEvent() { return true; }
}
function decorations(state, level) {
  if (!state.field(editorLivePreviewField, false)) return Decoration.none;
  const {blocks} = parseDocument(state.doc.toString());
  const ranges = [];
  for (const block of blocks) {
    const line = state.doc.line(block.start+1);
    ranges.push(Decoration.line({class:`HyperMD-header HyperMD-header-${level} evoldown-editor-heading`}).range(line.from));
    const editing = state.selection.ranges.some(range => range.from <= line.to && range.to >= line.from);
    if (!editing) ranges.push(Decoration.replace({widget:new HeadingWidget(block,blocks,level)}).range(line.from,line.to));
  }
  return Decoration.set(ranges,true);
}
module.exports = class EvoldownPlugin extends Plugin {
  async onload() {
    this.settings = {headingLevel: headingLevel((await this.loadData())?.headingLevel)};
    this.outline = new OutlineBridge(this);
    this.outline.start();
    this.editorViews = new Set();
    this.addSettingTab(new EvoldownSettingTab(this.app, this));
    const plugin = this;
    this.registerEditorExtension([
      ViewPlugin.fromClass(class {
        constructor(view) { this.view = view; plugin.editorViews.add(view); }
        destroy() { plugin.editorViews.delete(this.view); }
      }),
      StateField.define({
        create:state => decorations(state, plugin.settings.headingLevel),
        update(value, transaction) {
          return transaction.docChanged || transaction.selection || transaction.effects.some(effect => effect.is(refreshHeadings)) || transaction.startState.field(editorLivePreviewField,false) !== transaction.state.field(editorLivePreviewField,false)
            ? decorations(transaction.state, plugin.settings.headingLevel) : value;
        },
        provide:field => EditorView.decorations.from(field)
      })
    ]);
    this.registerMarkdownPostProcessor(async (element, context) => {
      if (element.closest('[data-evoldown-render]')) return;
      const info = context.getSectionInfo(element);
      if (!info) {
        await renderPdfExport(this,element,context,MarkdownRenderer,MarkdownRenderChild);
        return;
      }
      const parsed = parseDocument(info.text);
      const first = info.lineStart, last = info.lineEnd + 1;
      const blocks = parsed.blocks.filter(block => block.start < last && block.end > first);
      if (!blocks.length) return;
      const container = element.ownerDocument.createElement('div'); container.dataset.evoldownRender = 'true';
      const child = new MarkdownRenderChild(container); context.addChild(child);
      const render = async (start, end, parent) => {
        const markdown = parsed.lines.slice(start,end).join('\n');
        if (markdown.trim()) await MarkdownRenderer.render(this.app, markdown, parent, context.sourcePath, child);
      };
      let cursor = first;
      for (const block of blocks) {
        if (cursor < block.start) await render(cursor,block.start,container);
        const card = container.createDiv({cls:'evoldown-card'});
        card.dataset.evoldownLine = String(block.start);
        if (block.start < first) card.classList.add('evoldown-continuation');
        if (block.end > last) card.classList.add('evoldown-continues');
        if (block.start >= first) card.append(createHeader(element.ownerDocument,block,parsed.blocks,target => { void this.navigate(context.sourcePath,target,element); }, this.settings.headingLevel));
        await render(Math.max(first,block.start+1),Math.min(last,block.end),card.createDiv({cls:'evoldown-body'}));
        cursor = Math.min(last,block.end);
      }
      if (cursor < last) await render(cursor,last,container);
      element.replaceChildren(container);
    });
  }
  async setHeadingLevel(value) {
    this.settings.headingLevel = headingLevel(value);
    this.outline.refresh();
    for (const view of this.editorViews) view.dispatch({effects:refreshHeadings.of(null)});
    for (const leaf of this.app.workspace.getLeavesOfType('markdown')) {
      if (leaf.view instanceof MarkdownView) leaf.view.previewMode.rerender(true);
    }
    await this.saveData(this.settings);
  }
  async navigate(path, target, element) {
    const root = element.closest('.markdown-preview-view');
    const card = root?.querySelector('[data-evoldown-line="' + target.start + '"]:not(.evoldown-continuation)');
    if (card) { card.scrollIntoView({block:'center',behavior:'smooth'}); card.classList.remove('evoldown-highlight'); void card.offsetWidth; card.classList.add('evoldown-highlight'); return; }
    const file = this.app.vault.getFileByPath(path);
    if (!file) return;
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file,{state:{mode:'source'}, eState:{line:target.start}});
    if (leaf.view instanceof MarkdownView) { leaf.view.editor.setCursor({line:target.start,ch:0}); leaf.view.editor.scrollIntoView({from:{line:target.start,ch:0},to:{line:target.start,ch:0}},true); }
  }
};

},'./icons.json':function(module){module.exports={
  "d": [
    "m21.15 6.85c0-2.2056-1.7944-4-4-4-4.1765-0.01989-5.4993 5.7322-1.8147 7.5629-0.263 0.63631-0.4627 1.4421-0.6559 2.2215-0.1397 0.56337-0.2841 1.1459-0.4405 1.6084-0.0728 0.2155-0.1286 0.4813-0.1891 0.4813-0.5072-0.7362-0.8126-2.2507-1.0979-3.3161-0.47879-1.5358-0.72936-4.4237-2.8018-4.558-0.77422 7e-5 -1.3844 0.52253-1.8138 1.553-0.55019 1.254-0.75064 3.2421-1.3784 4.4472-0.39648 3e-4 -0.79576 0.0045-1.1877 0.0703-0.67978 0.1073-1.3339 0.4195-1.798 0.9347-0.39707 0.4315-0.6427 0.9874-0.74275 1.5623-0.063545 0.351-0.07691 0.7094-0.07883 1.0654 0.001935 0.4718-0.01324 0.9457 0.027745 1.4163 0.09435 1.151 0.65732 2.1308 1.7281 2.6237 0.43467 0.1975 0.91053 0.2877 1.3854 0.3129 0.40096 0.0215 0.80345 0.0129 1.2048 0.0139 0.6491 2e-4 1.2891-0.0515 1.888-0.3229 0.90042-0.4067 1.4845-1.2039 1.6712-2.1666 0.0761-0.3779 0.09179-0.7654 0.09344-1.15 7.7e-4 -0.2699 0.00148-0.5413-7.8e-4 -0.8111-0.00379-0.4854-0.04143-0.9771-0.19121-1.4414-0.28748-0.9172-0.98053-1.616-1.8964-1.909 0.43984-1.1576 0.66815-2.7594 1.1268-3.8895 0.3537 0.72804 0.57113 1.7669 0.82283 2.7298 0.26567 1.0724 0.5404 2.1814 0.90896 3.0557 0.87204 2.2985 3.1124 2.7586 4.0452 0.392 0.5508-1.2642 0.7508-3.279 1.3828-4.4916 2.1142-0.10339 3.8024-1.8557 3.8024-3.995zm-12.073 8.8023c0.05605 0.2275 0.06623 0.465 0.07092 0.6983 0.00363 0.2444 0.00195 0.4906 0.00214 0.735-0.0063 0.408 0.01486 0.882-0.18359 1.2496-0.24573 0.4539-0.8026 0.501-1.2651 0.5114-0.33714 0.0058-0.67525 0.0041-1.0124 0.0018-0.46455-0.0092-1.0361-0.0245-1.3192-0.4545-0.16612-0.2552-0.19733-0.5702-0.21202-0.8673-0.01004-0.2443-0.00683-0.4906-0.0075-0.735 5.9e-4 -0.2322-0.00201-0.4664 0.01171-0.6983 0.01886-0.2936 0.06332-0.6069 0.24969-0.8453 0.34185-0.4331 1.0226-0.3889 1.5228-0.3979 0.38828 0.0035 0.77905-0.0131 1.1658 0.0285 0.49865 0.0566 0.85211 0.2621 0.97684 0.7737zm8.0732-6.8023c-2.6379-0.06696-2.6373-3.9334 0-4 2.6378 0.06697 2.6373 3.9334 0 4z"
  ],
  "e": [
    "m21.9 15.621c0.1248-1.8535-0.6087-3.4099-2.6058-3.8292-0.7712-0.15744-1.3921-0.13977-2.1113-0.14543-0.6323 0.0048-1.1718-0.01567-1.8401 0.03203 1.5356-0.8078 1.6998-2.205 1.6567-3.546 0.1272-2.3708-1.4685-3.666-3.7727-3.673-2.2427-0.04024-5.0463-0.27229-5.9443 1.9172-0.28083 0.6692-0.27606 1.2179-0.28202 1.6587-0.08527 1.4303 0.20687 2.9224 1.662 3.6429-2.3051-0.05275-5.3273-0.39212-6.28 1.8983-0.28073 0.66862-0.27595 1.2174-0.282 1.6572-0.10329 1.6061 0.3059 3.171 2.0252 3.8067 1.2061 0.4187 2.2175 0.2869 3.3945 0.3134 2.0524 0.0901 4.0448-0.4637 4.4796-2.4982 0.609 2.5638 3.2086 2.5463 5.3204 2.4982 2.7823 0.1278 4.7024-0.9368 4.5798-3.7329zm-12.899-7.6287c-0.14889-1.8665 1.8839-1.4921 3.1358-1.546 0.8939 0.05358 2.4743-0.21158 2.8003 0.88445 0.2729 2.4494-0.0297 2.8555-2.5242 2.8232-0.94713-0.07259-2.869 0.28949-3.3134-0.77077-0.14881-0.44557-0.08538-0.92893-0.09846-1.3909zm0.2606 9.2128c-0.56638 0.162-1.1652 0.1412-1.7487 0.1488-0.59786-0.0036-1.1977 0.0131-1.7948-0.0233-0.93407-0.0365-1.6776-0.3579-1.6157-1.4217 0.01574-0.5119-0.06845-1.0551 0.11822-1.5436 0.4432-0.84155 1.5978-0.6728 2.4032-0.7191 0.81712 0.01614 1.6464-0.05154 2.4536 0.10154 0.99382 0.17537 1.0564 0.91742 1.0227 1.7752-6.1e-4 0.7729 0.04085 1.416-0.83867 1.6821zm2.9212-3.6286c-0.0836 0.19457-0.14194 0.3848-0.18279 0.56614-0.18535-0.87758-0.76293-1.6189-1.5605-2.02 1.0871 0.04933 2.0387 0.04959 3.1216-8e-5 -0.7672 0.39034-1.1687 0.96486-1.3783 1.4539zm6.8788 3.6286c-0.5664 0.162-1.1652 0.1412-1.7488 0.1488-0.5978-0.0036-1.1977 0.0131-1.7947-0.0233-0.9341-0.0365-1.6776-0.3579-1.6157-1.4217 0.0157-0.5119-0.0685-1.0551 0.1182-1.5436 0.4432-0.84155 1.5978-0.6728 2.4033-0.7191 0.8171 0.01614 1.6464-0.05154 2.4536 0.10154 0.9938 0.17537 1.0563 0.91742 1.0227 1.7752-6e-4 0.7729 0.0409 1.416-0.8386 1.6821z"
  ],
  "t": [
    "m15.385 10.538c-0.52922 1.222-0.74082 3.1121-1.2852 4.3107-0.06906-2e-5 -0.24102-0.40954-0.40553-0.85764-0.54849-1.4968-0.91293-3.7816-1.4977-5.2179-0.49825-1.7178-2.7313-2.8836-3.8104-0.24557-0.55221 1.2498-0.75261 3.2793-1.3921 4.4683-0.45354 0.09492-0.79418 0.49706-0.79418 0.9788 0 0.5523 0.4477 1 1 1 0.77414 0 1.3844-0.52246 1.8137-1.5529 0.50969-1.1819 0.73444-2.9587 1.2241-4.138 0.07175 2e-5 0.14687 0.33291 0.23664 0.59492 0.20698 0.60425 0.39119 1.3477 0.58618 2.1349 0.2657 1.0724 0.54043 2.1814 0.90899 3.0557 0.87212 2.2985 3.1123 2.7586 4.0452 0.39202 0.55283-1.2608 0.75203-3.309 1.3936-4.5083 0.4522-0.0959 0.7915-0.49744 0.7915-0.97823 0-0.55229-0.4477-1-1-1-0.7755 0-1.3861 0.526-1.8148 1.5634z",
    "m15.802 6.9697c-0.1557 0.1946-0.1882 0.58884 0.1331 0.60533 1.2616 0.02168 2.5193 0.48654 3.5913 1.2655 0.2705 0.19453 0.6808 0.05368 0.7176-0.30435 0.0793-0.76097 0.0572-1.5713-0.086-2.401-0.1456-0.82752-0.4109-1.6736-0.8018-2.5036-0.1536-0.34251-0.6624-0.55548-0.9204-0.23779l-0.7238 0.98277c-3.8989-2.9446-9.692-2.2836-12.827 1.4659-6.4518 7.8165 1.8281 18.818 11.123 14.783 1.8924-0.8564 3.4853-2.3528 4.4507-4.1927 0.0679-0.1218 0.1291-0.2481 0.1823-0.377 0.1017-0.2304 0.1549-0.518-0.0557-0.7052-0.1162-0.1043-0.2646-0.1628-0.4074-0.221-0.1475-0.0577-0.2953-0.116-0.4439-0.1706-0.2042-0.0713-0.4475-0.1531-0.6498-0.0358-0.0846 0.0496-0.1444 0.131-0.1982 0.2109-0.0747 0.1157-0.1266 0.2445-0.1952 0.3636-0.4837 0.9276-1.1717 1.74-1.9925 2.3831-0.8208 0.6431-1.7745 1.1169-2.7897 1.3673-7.0612 1.7198-12.182-6.5444-7.5021-12.107 2.4634-2.9539 7.0543-3.4782 10.119-1.154"
  ],
  "c": [
    "m6.825 4.8749c1.8175-0.03033 2.3249 0.02869 2.25 2.0152 0.01496 1.139 0.01338 1.984-1.3875 1.9798-1.6108-0.01491-2.7285 0.30288-2.6124-1.796-0.019-1.5193-0.04171-2.2697 1.7499-2.1989zm0-2c-2.5847-0.10689-3.8882 1.4181-3.7496 3.8782-0.058825 1.6262 0.20934 2.9456 1.5713 3.7018 0.98591 0.49526 1.6843 0.40204 2.4713 0.42016 0.661-0.00557 1.2079 0.02014 1.9275-0.21866 1.051-0.35295 1.7794-1.2693 1.9533-2.3675 0.08948-0.54803 0.07327-0.95095 0.0762-1.3975-0.00196-0.42752 0.01114-0.8053-0.05632-1.306-0.24162-1.9408-1.9089-2.8188-3.6634-2.7097-0.17686-7.9441e-4 -0.35349-2.3937e-4 -0.53038-7.7934e-4z",
    "m17.075 8.6749c1.8175-0.03034 2.3249 0.02868 2.25 2.0152 0.01495 1.139 0.01338 1.984-1.3875 1.9797-1.6108-0.01491-2.7285 0.30288-2.6124-1.796-0.01899-1.5193-0.04171-2.2697 1.7499-2.1989zm0-2c-2.5847-0.10689-3.8882 1.4181-3.7496 3.8782-0.05882 1.6262 0.20933 2.9457 1.5713 3.7017 0.98593 0.49528 1.6843 0.40205 2.4713 0.42017 0.66099-0.00556 1.2079 0.02015 1.9275-0.21865 1.051-0.35295 1.7794-1.2693 1.9533-2.3675 0.08949-0.54803 0.07328-0.95095 0.07621-1.3975-0.00197-0.42839 0.0112-0.80698-0.05673-1.3089-0.24288-1.9391-1.9097-2.8158-3.663-2.7068-0.17688-7.9346e-4 -0.35351-2.388e-4 -0.5304-7.7896e-4z",
    "m8.4749 15.525c1.8175-0.03033 2.3249 0.02868 2.25 2.0152 0.01496 1.139 0.01338 1.984-1.3875 1.9797-1.6108-0.01491-2.7285 0.30288-2.6124-1.796-0.01899-1.5193-0.04172-2.2697 1.7499-2.1989zm0-2c-2.5847-0.10689-3.8882 1.4181-3.7496 3.8782-0.058825 1.6262 0.20934 2.9456 1.5713 3.7018 0.98591 0.49526 1.6843 0.40203 2.4713 0.42016 0.66099-0.00557 1.2079 0.02014 1.9276-0.21866 1.051-0.35294 1.7794-1.2693 1.9533-2.3675 0.08949-0.54803 0.07328-0.95095 0.07621-1.3975-0.00197-0.42753 0.01113-0.80529-0.05633-1.306-0.24162-1.9408-1.9089-2.8188-3.6634-2.7097-0.17688-7.9346e-4 -0.35351-2.4262e-4 -0.5304-7.8736e-4z"
  ],
  "v": [
    "m12.006 2.4861c8.295-0.034635 12.587 10.042 6.9396 15.995 0.302-0.0792 0.5884 0.106 0.8099 0.2931 0.1763 0.1517 0.337 0.3223 0.4938 0.4938 0.1806 0.1987 0.3602 0.3999 0.5393 0.6 0.158 0.1775 0.3162 0.3571 0.4573 0.5485 0.0932 0.127 0.1803 0.2635 0.2402 0.4098 0.0591 0.1432 0.0867 0.3066 0.0463 0.4586l-0.0182 0.058c-0.0546 0.1443-0.1606 0.2646-0.2695 0.3712-0.0972 0.0941-0.2013 0.1853-0.3018 0.2759-0.1104 0.0982-0.2212 0.201-0.3417 0.287-0.1188 0.0852-0.2583 0.1531-0.4066 0.159-0.2688 9e-3 -0.5043-0.1558-0.7006-0.3227-0.1407-0.1218-0.2719-0.2564-0.3983-0.3929-0.2101-0.2279-0.4164-0.4606-0.6233-0.6914-0.1578-0.1777-0.3167-0.3566-0.4572-0.5485-0.0869-0.1186-0.1682-0.2449-0.2272-0.3799-0.06-0.136-0.0946-0.2901-0.0688-0.4385l0.0117-0.0521 0.0161-0.0498c-1.7182 1.3134-3.966 2.0444-6.2474 1.9119-12.23-1.0527-11.717-18.608 0.50643-18.986zm-6.8e-4 2c-3.9794 3.5e-4 -7.2654 3.1166-7.4809 7.0946-0.30103 4.0208 3.0533 7.76 7.0834 7.8947 4.1153 0.2383 7.6845-2.9602 7.8946-7.0833 0.319-4.1746-3.3113-8.0014-7.4964-7.9059",
    "m8.2769 7.8469c0.29326 0.69532 0.64074 1.1934 1.5 1.3397 0.4567-0.53241 1.0671-0.92645 1.7212-0.97652 0.65414-0.05007 1.1756 0.26304 1.2305 0.98096 0.10016 1.3082-2.47 2.532-1.899 4.9596 0.64656 0.38624 1.7475 0.36741 2.2073 0.03029-0.36861-2.09 2.575-3.1725 2.4052-5.3901-0.16975-2.2175-1.7734-3.0416-3.7676-2.8889-1.4358 0.10991-2.597 0.87279-3.3975 1.945z",
    "m12.01 14.568c-0.99198 0-1.696 0.76802-1.696 1.7601 0 0.992 0.70406 1.776 1.696 1.776 0.97603 0 1.696-0.78404 1.696-1.776 0-0.99204-0.72002-1.7601-1.696-1.7601z"
  ]
};}};
const cache = {};
function load(id){if(!factories[id])return externalRequire(id);if(cache[id])return cache[id].exports;const module={exports:{}};cache[id]=module;factories[id](module,module.exports,load);return module.exports;}
module.exports=load('./main');
